EnvironmentType=QAEnv

QAEnv=https://rahulshettyacademy.com
UATEnv=

AnalyticsRequired=N



################ DataBase Login Details ##################
DataBaseType=Oracle
JDBCDriver=oracle.jdbc.driver.OracleDriver
DBPasswordEnc=N
DatabaseAlias=
DatabaseUserName=
DatabasePassword=
DatabaseURL=
DBScriptsPath=.//src//test/resources//dbscripts//
DatabaseSID=
