EnvironmentType=QA
QA=https://rahulshettyacademy.com
UAT=

AnalyticsRequired=N

################ DataBase Login Details ##################
DataBaseType=Oracle
JDBCDriver=oracle.jdbc.driver.OracleDriver
DBPasswordEnc=N
DatabaseAlias=
DatabaseUserName=
DatabasePassword=
DatabaseURL=
DBScriptsPath=.//src//test/resources//dbFiles//
DatabaseSID=
Run_Region=UAT
tableName=AUTOMATION_RUN_DETAILS

